[2023-02-28T20:18:09.030+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: s3_upload_test.postgres_to_s3 manual__2023-02-28T20:18:07.907405+00:00 [queued]>
[2023-02-28T20:18:09.038+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: s3_upload_test.postgres_to_s3 manual__2023-02-28T20:18:07.907405+00:00 [queued]>
[2023-02-28T20:18:09.038+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-28T20:18:09.038+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-02-28T20:18:09.038+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-28T20:18:09.049+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2023-02-28 20:18:07.907405+00:00
[2023-02-28T20:18:09.053+0000] {standard_task_runner.py:55} INFO - Started process 1829 to run task
[2023-02-28T20:18:09.055+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 's3_upload_test', 'postgres_to_s3', 'manual__2023-02-28T20:18:07.907405+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/s3_upload_dag.py', '--cfg-path', '/tmp/tmpj5rf9ear']
[2023-02-28T20:18:09.055+0000] {standard_task_runner.py:83} INFO - Job 56: Subtask postgres_to_s3
[2023-02-28T20:18:09.102+0000] {task_command.py:388} INFO - Running <TaskInstance: s3_upload_test.postgres_to_s3 manual__2023-02-28T20:18:07.907405+00:00 [running]> on host 2341ffaf5508
[2023-02-28T20:18:09.159+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tem109
AIRFLOW_CTX_DAG_ID=s3_upload_test
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-02-28T20:18:07.907405+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-28T20:18:07.907405+00:00
[2023-02-28T20:18:09.166+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-02-28T20:18:09.179+0000] {s3_upload_dag.py:30} INFO - Saved orders data in text file: dags/get_orders_20230228.txt
[2023-02-28T20:18:09.179+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/s3_upload_dag.py", line 32, in postgres_to_s3
    s3_hook = S3Hook(aws_conn_id = "s3_conn")
NameError: name 'S3Hook' is not defined
[2023-02-28T20:18:09.186+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=s3_upload_test, task_id=postgres_to_s3, execution_date=20230228T201807, start_date=20230228T201809, end_date=20230228T201809
[2023-02-28T20:18:09.195+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 56 for task postgres_to_s3 (name 'S3Hook' is not defined; 1829)
[2023-02-28T20:18:09.226+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-28T20:18:09.241+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
