[2023-03-07T19:05:18.761+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Ingest_to_Snowflake.drop_warehouse manual__2023-03-07T18:41:14.393073+00:00 [queued]>
[2023-03-07T19:05:18.772+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Ingest_to_Snowflake.drop_warehouse manual__2023-03-07T18:41:14.393073+00:00 [queued]>
[2023-03-07T19:05:18.772+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-07T19:05:18.772+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 6
[2023-03-07T19:05:18.772+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-07T19:05:18.898+0000] {taskinstance.py:1300} INFO - Executing <Task(SnowflakeOperator): drop_warehouse> on 2023-03-07 18:41:14.393073+00:00
[2023-03-07T19:05:18.903+0000] {standard_task_runner.py:55} INFO - Started process 14142 to run task
[2023-03-07T19:05:18.905+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Ingest_to_Snowflake', 'drop_warehouse', 'manual__2023-03-07T18:41:14.393073+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/copy_into_snowflake.py', '--cfg-path', '/tmp/tmpctgyta84']
[2023-03-07T19:05:18.906+0000] {standard_task_runner.py:83} INFO - Job 206: Subtask drop_warehouse
[2023-03-07T19:05:18.945+0000] {task_command.py:388} INFO - Running <TaskInstance: Ingest_to_Snowflake.drop_warehouse manual__2023-03-07T18:41:14.393073+00:00 [running]> on host d7fd3210ba1e
[2023-03-07T19:05:18.991+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Ingest_to_Snowflake
AIRFLOW_CTX_TASK_ID=drop_warehouse
AIRFLOW_CTX_EXECUTION_DATE=2023-03-07T18:41:14.393073+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-07T18:41:14.393073+00:00
[2023-03-07T19:05:18.992+0000] {sql.py:254} INFO - Executing: ['\n    DROP WAREHOUSE my_wh;']
[2023-03-07T19:05:18.997+0000] {base.py:73} INFO - Using connection ID 'snowflake_conn' for task execution.
[2023-03-07T19:05:19.169+0000] {base.py:73} INFO - Using connection ID 'snowflake_conn' for task execution.
[2023-03-07T19:05:19.171+0000] {connection.py:287} INFO - Snowflake Connector for Python Version: 3.0.1, Python Version: 3.7.16, Platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-debian-11.6
[2023-03-07T19:05:19.172+0000] {connection.py:990} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-03-07T19:05:19.172+0000] {connection.py:1007} INFO - Setting use_openssl_only mode to False
[2023-03-07T19:05:19.835+0000] {cursor.py:738} INFO - query: [ALTER SESSION SET autocommit=False]
[2023-03-07T19:05:19.915+0000] {cursor.py:751} INFO - query execution done
[2023-03-07T19:05:19.915+0000] {cursor.py:891} INFO - Number of results in first chunk: 1
[2023-03-07T19:05:19.915+0000] {sql.py:375} INFO - Running statement: 
    DROP WAREHOUSE my_wh;, parameters: None
[2023-03-07T19:05:19.915+0000] {cursor.py:738} INFO - query: [DROP WAREHOUSE my_wh;]
[2023-03-07T19:05:20.020+0000] {cursor.py:751} INFO - query execution done
[2023-03-07T19:05:20.024+0000] {connection.py:586} INFO - closed
[2023-03-07T19:05:20.049+0000] {connection.py:589} INFO - No async queries seem to be running, deleting session
[2023-03-07T19:05:20.100+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 379, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/cursor.py", line 839, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 294, in errorhandler_wrapper
    error_value,
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 231, in default_errorhandler
    cursor=cursor,
snowflake.connector.errors.ProgrammingError: 002003 (02000): 01aacad9-0000-0ab4-0000-1e09000142ca: SQL compilation error:
Warehouse 'MY_WH' does not exist or not authorized.
[2023-03-07T19:05:20.107+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=Ingest_to_Snowflake, task_id=drop_warehouse, execution_date=20230307T184114, start_date=20230307T190518, end_date=20230307T190520
[2023-03-07T19:05:20.118+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 206 for task drop_warehouse (002003 (02000): 01aacad9-0000-0ab4-0000-1e09000142ca: SQL compilation error:
Warehouse 'MY_WH' does not exist or not authorized.; 14142)
[2023-03-07T19:05:20.159+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-07T19:05:20.174+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
