[2023-03-05T20:02:53.260+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: formula1_upload_to_s3.constructors_upload manual__2023-03-05T20:02:51.295856+00:00 [queued]>
[2023-03-05T20:02:53.274+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: formula1_upload_to_s3.constructors_upload manual__2023-03-05T20:02:51.295856+00:00 [queued]>
[2023-03-05T20:02:53.274+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-05T20:02:53.274+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-03-05T20:02:53.274+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-05T20:02:53.294+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): constructors_upload> on 2023-03-05 20:02:51.295856+00:00
[2023-03-05T20:02:53.302+0000] {standard_task_runner.py:55} INFO - Started process 10098 to run task
[2023-03-05T20:02:53.312+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'formula1_upload_to_s3', 'constructors_upload', 'manual__2023-03-05T20:02:51.295856+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/s3_upload_dag.py', '--cfg-path', '/tmp/tmpphtfewwz']
[2023-03-05T20:02:53.313+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask constructors_upload
[2023-03-05T20:02:53.459+0000] {task_command.py:388} INFO - Running <TaskInstance: formula1_upload_to_s3.constructors_upload manual__2023-03-05T20:02:51.295856+00:00 [running]> on host a4cedc34403c
[2023-03-05T20:02:53.563+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tem109
AIRFLOW_CTX_DAG_ID=formula1_upload_to_s3
AIRFLOW_CTX_TASK_ID=constructors_upload
AIRFLOW_CTX_EXECUTION_DATE=2023-03-05T20:02:51.295856+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-05T20:02:51.295856+00:00
[2023-03-05T20:02:53.588+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/s3_upload_dag.py", line 47, in constructors_upload
    conn = hook.get_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 117, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2023-03-05T20:02:53.594+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=formula1_upload_to_s3, task_id=constructors_upload, execution_date=20230305T200251, start_date=20230305T200253, end_date=20230305T200253
[2023-03-05T20:02:53.608+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 9 for task constructors_upload (The conn_id `postgres_localhost` isn't defined; 10098)
[2023-03-05T20:02:53.645+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-05T20:02:53.725+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
