[2023-03-07T18:17:24.237+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Ingest_to_Snowflake_v02.create_circuits_table scheduled__2023-03-06T00:00:00+00:00 [queued]>
[2023-03-07T18:17:24.587+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Ingest_to_Snowflake_v02.create_circuits_table scheduled__2023-03-06T00:00:00+00:00 [queued]>
[2023-03-07T18:17:24.588+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-07T18:17:24.588+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-03-07T18:17:24.588+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-07T18:17:24.601+0000] {taskinstance.py:1300} INFO - Executing <Task(SnowflakeOperator): create_circuits_table> on 2023-03-06 00:00:00+00:00
[2023-03-07T18:17:24.606+0000] {standard_task_runner.py:55} INFO - Started process 8577 to run task
[2023-03-07T18:17:24.609+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Ingest_to_Snowflake_v02', 'create_circuits_table', 'scheduled__2023-03-06T00:00:00+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/(not working) s3_to_snowflake.py', '--cfg-path', '/tmp/tmpylor_k4u']
[2023-03-07T18:17:24.611+0000] {standard_task_runner.py:83} INFO - Job 103: Subtask create_circuits_table
[2023-03-07T18:17:24.656+0000] {task_command.py:388} INFO - Running <TaskInstance: Ingest_to_Snowflake_v02.create_circuits_table scheduled__2023-03-06T00:00:00+00:00 [running]> on host d7fd3210ba1e
[2023-03-07T18:17:24.710+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Ingest_to_Snowflake_v02
AIRFLOW_CTX_TASK_ID=create_circuits_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-06T00:00:00+00:00
[2023-03-07T18:17:24.710+0000] {sql.py:254} INFO - Executing: ['sql/sql_statements.create_circuits_table', 'sql/sql_statements.start_warehouse']
[2023-03-07T18:17:24.717+0000] {base.py:73} INFO - Using connection ID 'snowflake_conn' for task execution.
[2023-03-07T18:17:24.906+0000] {base.py:73} INFO - Using connection ID 'snowflake_conn' for task execution.
[2023-03-07T18:17:24.907+0000] {connection.py:287} INFO - Snowflake Connector for Python Version: 3.0.1, Python Version: 3.7.16, Platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-debian-11.6
[2023-03-07T18:17:24.907+0000] {connection.py:990} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-03-07T18:17:24.907+0000] {connection.py:1007} INFO - Setting use_openssl_only mode to False
[2023-03-07T18:17:25.753+0000] {cursor.py:738} INFO - query: [ALTER SESSION SET autocommit=False]
[2023-03-07T18:17:25.872+0000] {cursor.py:751} INFO - query execution done
[2023-03-07T18:17:25.873+0000] {cursor.py:891} INFO - Number of results in first chunk: 1
[2023-03-07T18:17:25.873+0000] {sql.py:375} INFO - Running statement: sql/sql_statements.create_circuits_table, parameters: None
[2023-03-07T18:17:25.873+0000] {cursor.py:738} INFO - query: [sql/sql_statements.create_circuits_table]
[2023-03-07T18:17:26.030+0000] {cursor.py:751} INFO - query execution done
[2023-03-07T18:17:26.047+0000] {connection.py:586} INFO - closed
[2023-03-07T18:17:26.090+0000] {connection.py:589} INFO - No async queries seem to be running, deleting session
[2023-03-07T18:17:26.172+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 379, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/cursor.py", line 839, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 294, in errorhandler_wrapper
    error_value,
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 231, in default_errorhandler
    cursor=cursor,
snowflake.connector.errors.ProgrammingError: 001003 (42000): 01aacaa9-0000-0ab5-0000-1e09000130c6: SQL compilation error:
syntax error line 1 at position 0 unexpected 'sql'.
[2023-03-07T18:17:26.180+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=Ingest_to_Snowflake_v02, task_id=create_circuits_table, execution_date=20230306T000000, start_date=20230307T181724, end_date=20230307T181726
[2023-03-07T18:17:26.192+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 103 for task create_circuits_table (001003 (42000): 01aacaa9-0000-0ab5-0000-1e09000130c6: SQL compilation error:
syntax error line 1 at position 0 unexpected 'sql'.; 8577)
[2023-03-07T18:17:26.225+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-07T18:17:26.249+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
