[2023-03-07T00:00:01.604+0000] {processor.py:153} INFO - Started process (PID=334) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:00:01.605+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:00:01.605+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:00:01.605+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:00:02.004+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T00:00:02.181+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:00:02.180+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 152, in <module>
    create_constructors_table, create_races_table] >> [copy_into_circuits_table, copy_into_races_table, copy_into_constructors_table, copy_into_results_table] >> drop_warehouse
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2023-03-07T00:00:02.182+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:00:02.197+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.595 seconds
[2023-03-07T00:00:32.860+0000] {processor.py:153} INFO - Started process (PID=398) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:00:32.862+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:00:32.862+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:00:32.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:00:33.256+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T00:00:33.391+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:00:33.391+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 152, in <module>
    create_constructors_table, create_races_table] >> [copy_into_circuits_table, copy_into_races_table, copy_into_constructors_table, copy_into_results_table] >> drop_warehouse
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2023-03-07T00:00:33.391+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:00:33.405+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.547 seconds
[2023-03-07T00:01:04.122+0000] {processor.py:153} INFO - Started process (PID=462) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:01:04.122+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:01:04.122+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:01:04.122+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:01:04.523+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T00:01:04.657+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:01:04.657+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 152, in <module>
    create_constructors_table, create_races_table] >> [copy_into_circuits_table, copy_into_races_table, copy_into_constructors_table, copy_into_results_table] >> drop_warehouse
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2023-03-07T00:01:04.658+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:01:04.669+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.549 seconds
[2023-03-07T00:01:35.373+0000] {processor.py:153} INFO - Started process (PID=506) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:01:35.381+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:01:35.382+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:01:35.382+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:01:35.383+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:01:35.383+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 152
    create_constructors_table, create_races_table] >> [copy_into_circuits_table, copy_into_races_table, copy_into_constructors_table, copy_into_results_table] >> drop_warehouse
                                                 ^
SyntaxError: invalid syntax
[2023-03-07T00:01:35.383+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:01:35.398+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.026 seconds
[2023-03-07T00:01:37.417+0000] {processor.py:153} INFO - Started process (PID=507) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:01:37.418+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:01:37.418+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:01:37.418+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:01:37.838+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T00:01:37.972+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:01:37.972+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 152, in <module>
    create_constructors_table, create_races_table) >> [copy_into_circuits_table, copy_into_races_table, copy_into_constructors_table, copy_into_results_table] >> drop_warehouse
TypeError: unsupported operand type(s) for >>: 'tuple' and 'list'
[2023-03-07T00:01:37.973+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:01:37.987+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.572 seconds
[2023-03-07T00:01:41.431+0000] {processor.py:153} INFO - Started process (PID=530) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:01:41.431+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:01:41.432+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:01:41.432+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:01:41.433+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:01:41.433+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 152
    create_constructors_table, create_races_table) >> (copy_into_circuits_table, copy_into_races_table, copy_into_constructors_table, copy_into_results_table] >> drop_warehouse
                                                                                                                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:01:41.434+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:01:41.447+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:01:46.453+0000] {processor.py:153} INFO - Started process (PID=531) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:01:46.454+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:01:46.454+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:01:46.454+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:01:46.859+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T00:01:46.998+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:01:46.997+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 152, in <module>
    create_constructors_table, create_races_table) >> (copy_into_circuits_table, copy_into_races_table, copy_into_constructors_table, copy_into_results_table) >> drop_warehouse
TypeError: unsupported operand type(s) for >>: 'tuple' and 'tuple'
[2023-03-07T00:01:46.998+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:01:47.010+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.559 seconds
[2023-03-07T00:02:17.584+0000] {processor.py:153} INFO - Started process (PID=596) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:02:17.585+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:02:17.585+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:02:17.585+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:02:17.989+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T00:02:18.123+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:02:18.122+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 152, in <module>
    create_constructors_table, create_races_table) >> (copy_into_circuits_table, copy_into_races_table, copy_into_constructors_table, copy_into_results_table) >> drop_warehouse
TypeError: unsupported operand type(s) for >>: 'tuple' and 'tuple'
[2023-03-07T00:02:18.123+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:02:18.135+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.553 seconds
[2023-03-07T00:02:48.832+0000] {processor.py:153} INFO - Started process (PID=640) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:02:48.833+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:02:48.834+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:02:48.833+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:02:49.243+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T00:02:49.384+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:02:49.384+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 152, in <module>
    create_constructors_table, create_races_table) >> (copy_into_circuits_table, copy_into_races_table, copy_into_constructors_table, copy_into_results_table) >> drop_warehouse
TypeError: unsupported operand type(s) for >>: 'tuple' and 'tuple'
[2023-03-07T00:02:49.385+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:02:49.398+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.568 seconds
[2023-03-07T00:03:08.037+0000] {processor.py:153} INFO - Started process (PID=684) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:08.037+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:03:08.038+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:08.038+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:08.457+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T00:03:08.598+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:08.597+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153, in <module>
    copy_into_constructors_table, copy_into_results_table) >> drop_warehouse
TypeError: unsupported operand type(s) for >>: 'tuple' and 'tuple'
[2023-03-07T00:03:08.598+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:08.609+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.574 seconds
[2023-03-07T00:03:11.639+0000] {processor.py:153} INFO - Started process (PID=687) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:11.639+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:03:11.640+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:11.640+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:11.641+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:11.641+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:03:11.642+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:11.655+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.018 seconds
[2023-03-07T00:03:28.708+0000] {processor.py:153} INFO - Started process (PID=728) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:28.710+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:03:28.710+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:28.710+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:28.712+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:28.711+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:03:28.712+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:28.730+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.024 seconds
[2023-03-07T00:03:30.748+0000] {processor.py:153} INFO - Started process (PID=730) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:30.748+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:03:30.749+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:30.749+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:30.750+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:30.749+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:03:30.750+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:30.763+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.016 seconds
[2023-03-07T00:03:32.760+0000] {processor.py:153} INFO - Started process (PID=731) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:32.760+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:03:32.760+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:32.760+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:32.762+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:32.761+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:03:32.762+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:32.775+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:03:37.801+0000] {processor.py:153} INFO - Started process (PID=752) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:37.801+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:03:37.802+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:37.802+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:37.803+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:37.803+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:03:37.804+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:37.819+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.022 seconds
[2023-03-07T00:03:39.813+0000] {processor.py:153} INFO - Started process (PID=753) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:39.813+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:03:39.814+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:39.813+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:39.815+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:39.814+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:03:39.815+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:39.829+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.018 seconds
[2023-03-07T00:03:42.846+0000] {processor.py:153} INFO - Started process (PID=754) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:42.847+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:03:42.847+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:42.847+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:42.848+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:42.848+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:03:42.848+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:42.862+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:03:44.859+0000] {processor.py:153} INFO - Started process (PID=755) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:44.860+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:03:44.860+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:44.860+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:44.861+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:44.861+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:03:44.862+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:44.874+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:03:48.894+0000] {processor.py:153} INFO - Started process (PID=765) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:48.894+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:03:48.894+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:48.894+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:48.896+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:48.895+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:03:48.896+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:48.909+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.018 seconds
[2023-03-07T00:03:49.904+0000] {processor.py:153} INFO - Started process (PID=777) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:49.905+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:03:49.905+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:49.905+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:49.906+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:49.906+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:03:49.907+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:49.922+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.020 seconds
[2023-03-07T00:03:53.940+0000] {processor.py:153} INFO - Started process (PID=778) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:53.940+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:03:53.941+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:53.940+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:53.942+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:53.941+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:03:53.942+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:53.954+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.015 seconds
[2023-03-07T00:03:56.958+0000] {processor.py:153} INFO - Started process (PID=779) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:56.959+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:03:56.959+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:56.959+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:56.961+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:03:56.960+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:03:56.961+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:03:56.974+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.018 seconds
[2023-03-07T00:04:04.146+0000] {processor.py:153} INFO - Started process (PID=801) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:04.146+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:04:04.147+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:04:04.147+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:04.148+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:04:04.148+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:04:04.148+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:04.161+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:04:06.156+0000] {processor.py:153} INFO - Started process (PID=802) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:06.156+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:04:06.157+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:04:06.157+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:06.158+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:04:06.158+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:04:06.159+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:06.172+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.018 seconds
[2023-03-07T00:04:20.232+0000] {processor.py:153} INFO - Started process (PID=823) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:20.232+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:04:20.233+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:04:20.232+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:20.234+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:04:20.233+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:04:20.234+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:20.246+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:04:28.267+0000] {processor.py:153} INFO - Started process (PID=844) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:28.268+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:04:28.268+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:04:28.268+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:28.269+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:04:28.269+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:04:28.270+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:28.283+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:04:30.447+0000] {processor.py:153} INFO - Started process (PID=846) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:30.447+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:04:30.447+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:04:30.447+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:30.449+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:04:30.448+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:04:30.449+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:30.461+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:04:40.488+0000] {processor.py:153} INFO - Started process (PID=867) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:40.496+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:04:40.496+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:04:40.496+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:40.497+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:04:40.497+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:04:40.498+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:40.511+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.025 seconds
[2023-03-07T00:04:52.541+0000] {processor.py:153} INFO - Started process (PID=888) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:52.541+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:04:52.542+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:04:52.542+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:52.543+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:04:52.543+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:04:52.544+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:52.559+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.020 seconds
[2023-03-07T00:04:54.559+0000] {processor.py:153} INFO - Started process (PID=889) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:54.559+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:04:54.560+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:04:54.560+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:54.561+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:04:54.561+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:04:54.561+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:04:54.576+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.019 seconds
[2023-03-07T00:05:03.618+0000] {processor.py:153} INFO - Started process (PID=911) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:03.618+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:05:03.619+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:03.618+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:03.620+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:03.620+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:05:03.621+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:03.635+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.019 seconds
[2023-03-07T00:05:05.628+0000] {processor.py:153} INFO - Started process (PID=912) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:05.628+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:05:05.628+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:05.628+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:05.630+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:05.629+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:05:05.630+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:05.643+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:05:07.660+0000] {processor.py:153} INFO - Started process (PID=913) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:07.660+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:05:07.661+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:07.661+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:07.662+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:07.662+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:05:07.663+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:07.676+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:05:11.723+0000] {processor.py:153} INFO - Started process (PID=916) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:11.724+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:05:11.724+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:11.724+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:11.726+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:11.725+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:05:11.727+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:11.741+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.021 seconds
[2023-03-07T00:05:13.738+0000] {processor.py:153} INFO - Started process (PID=935) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:13.739+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:05:13.739+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:13.739+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:13.740+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:13.740+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:05:13.740+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:13.753+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:05:28.810+0000] {processor.py:153} INFO - Started process (PID=956) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:28.811+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:05:28.811+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:28.811+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:28.812+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:28.812+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:05:28.812+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:28.824+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.016 seconds
[2023-03-07T00:05:36.862+0000] {processor.py:153} INFO - Started process (PID=978) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:36.863+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:05:36.863+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:36.863+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:36.864+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:36.864+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:05:36.864+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:36.881+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.021 seconds
[2023-03-07T00:05:39.877+0000] {processor.py:153} INFO - Started process (PID=979) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:39.877+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:05:39.878+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:39.878+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:39.879+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:39.879+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:05:39.880+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:39.892+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.018 seconds
[2023-03-07T00:05:42.894+0000] {processor.py:153} INFO - Started process (PID=980) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:42.895+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:05:42.895+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:42.895+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:42.897+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:42.896+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:05:42.897+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:42.912+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.021 seconds
[2023-03-07T00:05:44.919+0000] {processor.py:153} INFO - Started process (PID=981) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:44.919+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:05:44.920+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:44.920+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:44.921+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:44.921+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:05:44.921+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:44.935+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.018 seconds
[2023-03-07T00:05:45.934+0000] {processor.py:153} INFO - Started process (PID=982) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:45.934+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:05:45.934+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:45.934+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:45.936+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:45.935+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:05:45.936+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:45.950+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.018 seconds
[2023-03-07T00:05:47.959+0000] {processor.py:153} INFO - Started process (PID=992) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:47.959+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:05:47.960+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:47.960+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:47.962+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:47.961+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:05:47.962+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:47.975+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:05:51.981+0000] {processor.py:153} INFO - Started process (PID=1004) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:51.981+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:05:51.982+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:51.982+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:51.983+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:51.983+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:05:51.983+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:51.997+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.018 seconds
[2023-03-07T00:05:58.019+0000] {processor.py:153} INFO - Started process (PID=1005) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:58.020+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:05:58.020+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:58.020+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:58.021+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:05:58.021+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:05:58.022+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:05:58.033+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.016 seconds
[2023-03-07T00:06:12.295+0000] {processor.py:153} INFO - Started process (PID=1036) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:12.296+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:06:12.296+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:12.296+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:12.298+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:12.297+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:06:12.298+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:12.310+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:06:14.307+0000] {processor.py:153} INFO - Started process (PID=1048) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:14.307+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:06:14.307+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:14.307+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:14.309+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:14.308+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:06:14.309+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:14.322+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:06:24.366+0000] {processor.py:153} INFO - Started process (PID=1069) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:24.366+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:06:24.366+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:24.366+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:24.368+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:24.367+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:06:24.368+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:24.381+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:06:27.382+0000] {processor.py:153} INFO - Started process (PID=1070) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:27.382+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:06:27.383+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:27.383+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:27.384+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:27.384+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:06:27.384+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:27.397+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:06:31.416+0000] {processor.py:153} INFO - Started process (PID=1071) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:31.416+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:06:31.417+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:31.416+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:31.418+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:31.418+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:06:31.418+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:31.430+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.016 seconds
[2023-03-07T00:06:38.468+0000] {processor.py:153} INFO - Started process (PID=1093) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:38.468+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:06:38.469+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:38.469+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:38.470+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:38.470+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:06:38.471+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:38.483+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:06:40.477+0000] {processor.py:153} INFO - Started process (PID=1094) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:40.478+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:06:40.478+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:40.478+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:40.480+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:40.479+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:06:40.480+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:40.494+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.018 seconds
[2023-03-07T00:06:43.510+0000] {processor.py:153} INFO - Started process (PID=1095) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:43.510+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:06:43.511+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:43.511+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:43.512+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:43.512+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:06:43.513+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:43.525+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:06:49.541+0000] {processor.py:153} INFO - Started process (PID=1116) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:49.542+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:06:49.542+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:49.542+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:49.543+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:49.543+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:06:49.544+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:49.556+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.016 seconds
[2023-03-07T00:06:51.557+0000] {processor.py:153} INFO - Started process (PID=1117) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:51.558+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:06:51.558+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:51.558+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:51.560+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:51.559+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:06:51.560+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:51.572+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:06:54.585+0000] {processor.py:153} INFO - Started process (PID=1118) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:54.585+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:06:54.586+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:54.586+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:54.587+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:06:54.587+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:06:54.588+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:06:54.599+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.016 seconds
[2023-03-07T00:07:00.615+0000] {processor.py:153} INFO - Started process (PID=1139) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:00.615+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:07:00.615+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:00.615+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:00.617+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:00.616+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:07:00.617+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:00.631+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.018 seconds
[2023-03-07T00:07:02.649+0000] {processor.py:153} INFO - Started process (PID=1141) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:02.650+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:07:02.650+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:02.650+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:02.652+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:02.651+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:07:02.652+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:02.666+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.018 seconds
[2023-03-07T00:07:14.701+0000] {processor.py:153} INFO - Started process (PID=1162) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:14.701+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:07:14.702+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:14.702+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:14.703+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:14.703+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:07:14.703+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:14.716+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:07:19.730+0000] {processor.py:153} INFO - Started process (PID=1163) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:19.730+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:07:19.731+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:19.731+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:19.732+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:19.731+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:07:19.732+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:19.746+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:07:21.747+0000] {processor.py:153} INFO - Started process (PID=1164) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:21.747+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:07:21.748+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:21.747+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:21.749+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:21.748+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:07:21.749+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:21.762+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.018 seconds
[2023-03-07T00:07:24.774+0000] {processor.py:153} INFO - Started process (PID=1185) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:24.774+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:07:24.775+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:24.775+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:24.776+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:24.775+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:07:24.776+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:24.788+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.016 seconds
[2023-03-07T00:07:41.867+0000] {processor.py:153} INFO - Started process (PID=1207) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:41.867+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:07:41.868+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:41.868+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:41.869+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:41.869+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:07:41.869+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:41.882+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:07:46.889+0000] {processor.py:153} INFO - Started process (PID=1217) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:46.889+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:07:46.890+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:46.890+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:46.891+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:46.891+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:07:46.892+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:46.907+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.020 seconds
[2023-03-07T00:07:50.919+0000] {processor.py:153} INFO - Started process (PID=1229) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:50.919+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:07:50.919+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:50.919+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:50.921+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:50.920+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:07:50.921+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:50.933+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.016 seconds
[2023-03-07T00:07:52.939+0000] {processor.py:153} INFO - Started process (PID=1230) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:52.939+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:07:52.940+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:52.939+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:52.941+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:52.941+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:07:52.941+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:52.955+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.018 seconds
[2023-03-07T00:07:55.962+0000] {processor.py:153} INFO - Started process (PID=1231) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:55.962+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:07:55.962+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:55.962+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:55.964+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:55.963+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:07:55.964+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:55.976+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.016 seconds
[2023-03-07T00:07:59.988+0000] {processor.py:153} INFO - Started process (PID=1252) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:59.988+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:07:59.988+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:59.988+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:07:59.990+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:07:59.989+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:07:59.990+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:08:00.003+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.017 seconds
[2023-03-07T00:08:06.036+0000] {processor.py:153} INFO - Started process (PID=1254) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:08:06.037+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:08:06.037+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:08:06.037+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:08:06.039+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:08:06.038+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:08:06.039+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:08:06.053+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.019 seconds
[2023-03-07T00:08:11.078+0000] {processor.py:153} INFO - Started process (PID=1275) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:08:11.079+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:08:11.079+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:08:11.079+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:08:11.081+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:08:11.080+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:08:11.081+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:08:11.096+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.020 seconds
[2023-03-07T00:08:20.116+0000] {processor.py:153} INFO - Started process (PID=1276) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:08:20.116+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:08:20.117+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:08:20.117+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:08:20.119+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:08:20.118+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:08:20.119+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:08:20.132+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.018 seconds
[2023-03-07T00:08:22.137+0000] {processor.py:153} INFO - Started process (PID=1284) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:08:22.137+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:08:22.137+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:08:22.137+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:08:22.139+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:08:22.138+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/s3_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_to_snowflake.py", line 153
    copy_into_constructors_table, copy_into_results_table) >>
                                                             ^
SyntaxError: invalid syntax
[2023-03-07T00:08:22.139+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:08:22.152+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.018 seconds
[2023-03-07T00:08:25.161+0000] {processor.py:153} INFO - Started process (PID=1298) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:08:25.162+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:08:25.162+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:08:25.162+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:08:25.576+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T00:08:25.721+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:08:25.857+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:08:25.857+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:Ingest_to_Snowflake
[2023-03-07T00:08:25.865+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:08:25.865+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:Ingest_to_Snowflake
[2023-03-07T00:08:25.871+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:08:25.871+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:Ingest_to_Snowflake
[2023-03-07T00:08:25.872+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:08:25.871+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T00:08:25.882+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:08:25.882+0000] {dag.py:2711} INFO - Creating ORM DAG for Ingest_to_Snowflake
[2023-03-07T00:08:25.892+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:08:25.892+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-06T00:00:00+00:00, run_after=2023-03-07T00:00:00+00:00
[2023-03-07T00:08:25.907+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.748 seconds
[2023-03-07T00:08:56.281+0000] {processor.py:153} INFO - Started process (PID=1342) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:08:56.281+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:08:56.282+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:08:56.282+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:08:56.704+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T00:08:56.846+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:08:56.872+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:08:56.872+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T00:08:56.891+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:08:56.891+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-06T00:00:00+00:00, run_after=2023-03-07T00:00:00+00:00
[2023-03-07T00:08:56.907+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.628 seconds
[2023-03-07T00:09:27.511+0000] {processor.py:153} INFO - Started process (PID=1406) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:09:27.512+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:09:27.512+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:09:27.512+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:09:27.929+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T00:09:28.075+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:09:28.099+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:09:28.099+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T00:09:28.118+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:09:28.118+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-06T00:00:00+00:00, run_after=2023-03-07T00:00:00+00:00
[2023-03-07T00:09:28.130+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.621 seconds
[2023-03-07T00:09:58.757+0000] {processor.py:153} INFO - Started process (PID=1470) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:09:58.757+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T00:09:58.758+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:09:58.758+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:09:59.406+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T00:09:59.601+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T00:09:59.641+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:09:59.640+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T00:09:59.672+0000] {logging_mixin.py:137} INFO - [2023-03-07T00:09:59.672+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-06T00:00:00+00:00, run_after=2023-03-07T00:00:00+00:00
[2023-03-07T00:09:59.688+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.934 seconds
[2023-03-07T16:02:51.320+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:02:51.321+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:02:51.321+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:02:51.321+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:02:51.856+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:02:52.165+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:02:52.244+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:02:52.243+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:02:52.268+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:02:52.268+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-06T00:00:00+00:00, run_after=2023-03-07T00:00:00+00:00
[2023-03-07T16:02:52.287+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.970 seconds
[2023-03-07T16:03:22.861+0000] {processor.py:153} INFO - Started process (PID=107) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:03:22.861+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:03:22.862+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:03:22.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:03:23.267+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:03:23.408+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:03:23.433+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:03:23.433+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:03:23.451+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:03:23.451+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-06T00:00:00+00:00, run_after=2023-03-07T00:00:00+00:00
[2023-03-07T16:03:23.472+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.613 seconds
[2023-03-07T16:03:54.104+0000] {processor.py:153} INFO - Started process (PID=160) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:03:54.104+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:03:54.104+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:03:54.104+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:03:54.588+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:03:54.785+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:03:54.809+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:03:54.809+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:03:54.830+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:03:54.830+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-06T00:00:00+00:00, run_after=2023-03-07T00:00:00+00:00
[2023-03-07T16:03:54.845+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.743 seconds
[2023-03-07T16:04:25.365+0000] {processor.py:153} INFO - Started process (PID=215) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:04:25.365+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:04:25.366+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:04:25.366+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:04:25.808+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:04:25.951+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:04:25.976+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:04:25.976+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:04:25.995+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:04:25.995+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-06T00:00:00+00:00, run_after=2023-03-07T00:00:00+00:00
[2023-03-07T16:04:26.009+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.647 seconds
[2023-03-07T16:04:56.676+0000] {processor.py:153} INFO - Started process (PID=279) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:04:56.676+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:04:56.677+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:04:56.677+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:04:57.144+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:04:57.302+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:04:57.327+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:04:57.327+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:04:57.348+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:04:57.347+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-06T00:00:00+00:00, run_after=2023-03-07T00:00:00+00:00
[2023-03-07T16:04:57.375+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.703 seconds
[2023-03-07T16:05:27.980+0000] {processor.py:153} INFO - Started process (PID=323) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:05:27.980+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:05:27.981+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:05:27.981+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:05:28.387+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:05:28.539+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:05:28.563+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:05:28.562+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:05:28.581+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:05:28.581+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-06T00:00:00+00:00, run_after=2023-03-07T00:00:00+00:00
[2023-03-07T16:05:28.595+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.617 seconds
[2023-03-07T16:05:59.237+0000] {processor.py:153} INFO - Started process (PID=387) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:05:59.238+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:05:59.238+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:05:59.238+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:05:59.678+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:05:59.830+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:05:59.854+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:05:59.854+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:05:59.872+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:05:59.872+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-06T00:00:00+00:00, run_after=2023-03-07T00:00:00+00:00
[2023-03-07T16:05:59.887+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.652 seconds
[2023-03-07T16:06:30.490+0000] {processor.py:153} INFO - Started process (PID=451) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:06:30.490+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:06:30.491+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:06:30.490+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:06:30.925+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:06:31.091+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:06:31.117+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:06:31.116+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:06:31.140+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:06:31.139+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-06T00:00:00+00:00, run_after=2023-03-07T00:00:00+00:00
[2023-03-07T16:06:31.155+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.667 seconds
[2023-03-07T16:07:01.749+0000] {processor.py:153} INFO - Started process (PID=495) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:07:01.749+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:07:01.750+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:07:01.749+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:07:02.170+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:07:02.317+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:07:02.342+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:07:02.342+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:07:02.363+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:07:02.363+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-06T00:00:00+00:00, run_after=2023-03-07T00:00:00+00:00
[2023-03-07T16:07:02.376+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.629 seconds
[2023-03-07T16:07:33.033+0000] {processor.py:153} INFO - Started process (PID=559) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:07:33.035+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:07:33.035+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:07:33.035+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:07:33.437+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:07:33.631+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:07:33.653+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:07:33.652+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:07:33.672+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:07:33.672+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-06T00:00:00+00:00, run_after=2023-03-07T00:00:00+00:00
[2023-03-07T16:07:33.687+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.656 seconds
[2023-03-07T16:08:04.278+0000] {processor.py:153} INFO - Started process (PID=610) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:08:04.286+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:08:04.287+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:08:04.287+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:08:04.768+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:08:04.916+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:08:04.941+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:08:04.940+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:08:04.965+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:08:04.965+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-06T00:00:00+00:00, run_after=2023-03-07T00:00:00+00:00
[2023-03-07T16:08:04.980+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.703 seconds
[2023-03-07T16:08:35.515+0000] {processor.py:153} INFO - Started process (PID=668) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:08:35.516+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:08:35.516+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:08:35.516+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:08:35.926+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:08:36.064+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:08:36.089+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:08:36.089+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:08:36.113+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:08:36.112+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-06T00:00:00+00:00, run_after=2023-03-07T00:00:00+00:00
[2023-03-07T16:08:36.135+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.621 seconds
[2023-03-07T16:09:06.753+0000] {processor.py:153} INFO - Started process (PID=736) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:09:06.755+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:09:06.755+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:09:06.755+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:09:07.210+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:09:07.368+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:09:07.394+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:09:07.393+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:09:07.418+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:09:07.418+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:09:07.435+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.684 seconds
[2023-03-07T16:09:38.013+0000] {processor.py:153} INFO - Started process (PID=780) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:09:38.013+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:09:38.013+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:09:38.013+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:09:38.420+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:09:38.564+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:09:38.669+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:09:38.668+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:09:38.693+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:09:38.693+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:09:38.707+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.697 seconds
[2023-03-07T16:10:09.297+0000] {processor.py:153} INFO - Started process (PID=844) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:10:09.297+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:10:09.298+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:10:09.298+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:10:09.722+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:10:09.862+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:10:09.884+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:10:09.884+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:10:09.904+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:10:09.904+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:10:09.917+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.623 seconds
[2023-03-07T16:10:27.464+0000] {processor.py:153} INFO - Started process (PID=868) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:10:27.464+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:10:27.464+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:10:27.464+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:10:27.916+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:10:28.087+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:10:28.151+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:10:28.150+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:10:28.173+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:10:28.172+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:10:28.190+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.728 seconds
[2023-03-07T16:10:31.220+0000] {processor.py:153} INFO - Started process (PID=891) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:10:31.220+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:10:31.221+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:10:31.221+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:10:31.626+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:10:31.767+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:10:31.774+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:10:31.774+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:10:31.793+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:10:31.793+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:10:31.808+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.589 seconds
[2023-03-07T16:11:01.886+0000] {processor.py:153} INFO - Started process (PID=935) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:11:01.888+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:11:01.888+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:11:01.888+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:11:02.336+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:11:02.488+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:11:02.546+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:11:02.545+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:11:02.567+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:11:02.567+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:11:02.584+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.700 seconds
[2023-03-07T16:11:32.995+0000] {processor.py:153} INFO - Started process (PID=999) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:11:32.996+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:11:32.997+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:11:32.997+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:11:33.391+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:11:33.538+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:11:33.565+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:11:33.564+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:11:33.585+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:11:33.585+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:11:33.600+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.608 seconds
[2023-03-07T16:12:04.243+0000] {processor.py:153} INFO - Started process (PID=1052) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:12:04.251+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:12:04.251+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:12:04.251+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:12:04.691+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:12:04.839+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:12:04.864+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:12:04.863+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:12:04.883+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:12:04.883+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:12:04.898+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.658 seconds
[2023-03-07T16:12:35.555+0000] {processor.py:153} INFO - Started process (PID=1107) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:12:35.562+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:12:35.563+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:12:35.563+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:12:35.961+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:12:36.100+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:12:36.122+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:12:36.122+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:12:36.142+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:12:36.142+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:12:36.158+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.605 seconds
[2023-03-07T16:13:06.782+0000] {processor.py:153} INFO - Started process (PID=1171) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:13:06.782+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:13:06.783+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:13:06.783+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:13:07.171+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:13:07.317+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:13:07.341+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:13:07.340+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:13:07.361+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:13:07.361+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:13:07.375+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.595 seconds
[2023-03-07T16:13:38.035+0000] {processor.py:153} INFO - Started process (PID=1215) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:13:38.036+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:13:38.037+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:13:38.037+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:13:38.527+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:13:38.672+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:13:38.702+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:13:38.702+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:13:38.724+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:13:38.724+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:13:38.739+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.706 seconds
[2023-03-07T16:14:09.295+0000] {processor.py:153} INFO - Started process (PID=1285) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:14:09.295+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:14:09.295+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:14:09.295+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:14:09.697+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:14:09.836+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:14:09.862+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:14:09.862+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:14:09.881+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:14:09.881+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:14:09.902+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.609 seconds
[2023-03-07T16:14:40.557+0000] {processor.py:153} INFO - Started process (PID=1350) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:14:40.558+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:14:40.558+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:14:40.558+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:14:40.950+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:14:41.084+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:14:41.107+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:14:41.106+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:14:41.127+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:14:41.127+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:14:41.147+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.592 seconds
[2023-03-07T16:15:11.829+0000] {processor.py:153} INFO - Started process (PID=1394) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:15:11.829+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:15:11.830+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:15:11.830+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:15:12.240+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:15:12.380+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:15:12.402+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:15:12.402+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:15:12.423+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:15:12.423+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:15:12.443+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.616 seconds
[2023-03-07T16:15:43.083+0000] {processor.py:153} INFO - Started process (PID=1458) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:15:43.083+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:15:43.084+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:15:43.084+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:15:43.487+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:15:43.625+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:15:43.647+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:15:43.647+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:15:43.666+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:15:43.665+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:15:43.679+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.598 seconds
[2023-03-07T16:16:14.323+0000] {processor.py:153} INFO - Started process (PID=1522) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:16:14.331+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:16:14.332+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:16:14.332+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:16:14.777+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:16:14.921+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:16:14.946+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:16:14.946+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:16:14.968+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:16:14.967+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:16:14.983+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.662 seconds
[2023-03-07T16:16:45.568+0000] {processor.py:153} INFO - Started process (PID=1567) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:16:45.568+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:16:45.569+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:16:45.569+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:16:45.961+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:16:46.098+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:16:46.119+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:16:46.119+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:16:46.138+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:16:46.138+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:16:46.151+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.584 seconds
[2023-03-07T16:17:16.809+0000] {processor.py:153} INFO - Started process (PID=1631) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:17:16.810+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:17:16.810+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:17:16.810+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:17:17.213+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:17:17.383+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:17:17.408+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:17:17.408+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:17:17.430+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:17:17.430+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:17:17.444+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.637 seconds
[2023-03-07T16:17:20.957+0000] {processor.py:153} INFO - Started process (PID=1634) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:17:20.957+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:17:20.957+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:17:20.957+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:17:21.392+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:17:21.530+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:17:21.554+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:17:21.553+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:17:21.574+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:17:21.574+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:17:21.591+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.635 seconds
[2023-03-07T16:17:51.714+0000] {processor.py:153} INFO - Started process (PID=1702) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:17:51.715+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:17:51.715+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:17:51.715+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:17:52.122+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:17:52.266+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:17:52.293+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:17:52.293+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:17:52.313+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:17:52.313+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:17:52.328+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.615 seconds
[2023-03-07T16:18:09.934+0000] {processor.py:153} INFO - Started process (PID=1726) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:18:09.934+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:18:09.935+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:18:09.935+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:18:10.323+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:18:10.461+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:18:10.511+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:18:10.510+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:18:10.528+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:18:10.528+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:18:10.543+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.611 seconds
[2023-03-07T16:18:19.592+0000] {processor.py:153} INFO - Started process (PID=1749) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:18:19.592+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:18:19.593+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:18:19.593+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:18:19.979+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:18:20.116+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:18:20.123+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:18:20.123+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:18:20.141+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:18:20.141+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:18:20.157+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.567 seconds
[2023-03-07T16:18:50.212+0000] {processor.py:153} INFO - Started process (PID=1817) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:18:50.213+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:18:50.213+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:18:50.213+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:18:50.656+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:18:50.829+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:18:50.886+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:18:50.886+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:18:50.916+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:18:50.916+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:18:50.938+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.728 seconds
[2023-03-07T16:19:21.321+0000] {processor.py:153} INFO - Started process (PID=1861) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:19:21.321+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:19:21.322+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:19:21.322+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:19:21.763+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:19:21.912+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:19:21.938+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:19:21.937+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:19:21.958+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:19:21.958+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:19:21.975+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.656 seconds
[2023-03-07T16:19:52.608+0000] {processor.py:153} INFO - Started process (PID=1925) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:19:52.608+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:19:52.609+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:19:52.609+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:19:53.014+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:19:53.153+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:19:53.177+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:19:53.177+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:19:53.198+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:19:53.198+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:19:53.213+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.606 seconds
[2023-03-07T16:20:23.854+0000] {processor.py:153} INFO - Started process (PID=1989) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:20:23.855+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:20:23.855+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:20:23.855+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:20:24.306+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:20:24.449+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:20:24.473+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:20:24.472+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:20:24.499+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:20:24.499+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:20:24.515+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.663 seconds
[2023-03-07T16:20:55.133+0000] {processor.py:153} INFO - Started process (PID=2033) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:20:55.135+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:20:55.135+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:20:55.135+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:20:55.529+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:20:55.666+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:20:55.690+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:20:55.690+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:20:55.710+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:20:55.710+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:20:55.731+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.600 seconds
[2023-03-07T16:21:26.335+0000] {processor.py:153} INFO - Started process (PID=2097) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:21:26.335+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:21:26.335+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:21:26.335+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:21:26.718+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:21:26.863+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:21:26.888+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:21:26.888+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:21:26.908+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:21:26.908+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:21:26.921+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.589 seconds
[2023-03-07T16:21:57.587+0000] {processor.py:153} INFO - Started process (PID=2141) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:21:57.588+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:21:57.588+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:21:57.588+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:21:58.091+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:21:58.248+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:21:58.278+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:21:58.278+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:21:58.301+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:21:58.300+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:21:58.315+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.730 seconds
[2023-03-07T16:22:28.853+0000] {processor.py:153} INFO - Started process (PID=2205) to work on /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:22:28.861+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/s3_to_snowflake.py for tasks to queue
[2023-03-07T16:22:28.861+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:22:28.861+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:22:29.249+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108 UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2023-03-07T16:22:29.388+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Ingest_to_Snowflake']) retrieved from /opt/airflow/dags/s3_to_snowflake.py
[2023-03-07T16:22:29.411+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:22:29.410+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-07T16:22:29.429+0000] {logging_mixin.py:137} INFO - [2023-03-07T16:22:29.429+0000] {dag.py:3441} INFO - Setting next_dagrun for Ingest_to_Snowflake to 2023-03-07T00:00:00+00:00, run_after=2023-03-08T00:00:00+00:00
[2023-03-07T16:22:29.443+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/s3_to_snowflake.py took 0.592 seconds
