[2023-03-07T18:45:40.595+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Ingest_to_Snowflake.copy_into_results_table manual__2023-03-07T18:20:20.496224+00:00 [queued]>
[2023-03-07T18:45:40.604+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Ingest_to_Snowflake.copy_into_results_table manual__2023-03-07T18:20:20.496224+00:00 [queued]>
[2023-03-07T18:45:40.604+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-07T18:45:40.604+0000] {taskinstance.py:1280} INFO - Starting attempt 6 of 6
[2023-03-07T18:45:40.604+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-07T18:45:40.734+0000] {taskinstance.py:1300} INFO - Executing <Task(S3ToSnowflakeOperator): copy_into_results_table> on 2023-03-07 18:20:20.496224+00:00
[2023-03-07T18:45:40.739+0000] {standard_task_runner.py:55} INFO - Started process 11998 to run task
[2023-03-07T18:45:40.741+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Ingest_to_Snowflake', 'copy_into_results_table', 'manual__2023-03-07T18:20:20.496224+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/copy_into_snowflake.py', '--cfg-path', '/tmp/tmp5yjo8zfc']
[2023-03-07T18:45:40.742+0000] {standard_task_runner.py:83} INFO - Job 186: Subtask copy_into_results_table
[2023-03-07T18:45:40.783+0000] {task_command.py:388} INFO - Running <TaskInstance: Ingest_to_Snowflake.copy_into_results_table manual__2023-03-07T18:20:20.496224+00:00 [running]> on host d7fd3210ba1e
[2023-03-07T18:45:40.833+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Ingest_to_Snowflake
AIRFLOW_CTX_TASK_ID=copy_into_results_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-07T18:20:20.496224+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-07T18:20:20.496224+00:00
[2023-03-07T18:45:40.834+0000] {s3_to_snowflake.py:146} INFO - Executing COPY command...
[2023-03-07T18:45:40.840+0000] {base.py:73} INFO - Using connection ID 'snowflake_conn' for task execution.
[2023-03-07T18:45:40.841+0000] {connection.py:287} INFO - Snowflake Connector for Python Version: 3.0.1, Python Version: 3.7.16, Platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-debian-11.6
[2023-03-07T18:45:40.842+0000] {connection.py:990} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-03-07T18:45:40.842+0000] {connection.py:1007} INFO - Setting use_openssl_only mode to False
[2023-03-07T18:45:41.417+0000] {cursor.py:738} INFO - query: [ALTER SESSION SET autocommit=True]
[2023-03-07T18:45:41.585+0000] {cursor.py:751} INFO - query execution done
[2023-03-07T18:45:41.585+0000] {cursor.py:891} INFO - Number of results in first chunk: 1
[2023-03-07T18:45:41.586+0000] {sql.py:375} INFO - Running statement: COPY INTO PUBLIC.results
FROM @formula_1_stage/
files=('results.csv')
file_format=generic_csv, parameters: None
[2023-03-07T18:45:41.586+0000] {cursor.py:738} INFO - query: [COPY INTO PUBLIC.results FROM @formula_1_stage/ files=('results.csv') file_forma...]
[2023-03-07T18:45:42.095+0000] {cursor.py:751} INFO - query execution done
[2023-03-07T18:45:42.101+0000] {connection.py:586} INFO - closed
[2023-03-07T18:45:42.129+0000] {connection.py:589} INFO - No async queries seem to be running, deleting session
[2023-03-07T18:45:42.206+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/snowflake/transfers/s3_to_snowflake.py", line 147, in execute
    snowflake_hook.run(copy_query, self.autocommit)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 379, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/cursor.py", line 839, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 294, in errorhandler_wrapper
    error_value,
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 231, in default_errorhandler
    cursor=cursor,
snowflake.connector.errors.ProgrammingError: 100080 (22000): 01aacac5-0000-0ab5-0000-1e09000131e2: Number of columns in file (14) does not match that of the corresponding table (9), use file format option error_on_column_count_mismatch=false to ignore this error
  File 'results.csv', line 3, character 1
  Row 1 starts at line 2, column "RESULTS"[14]
  If you would like to continue loading when an error is encountered, use other values such as 'SKIP_FILE' or 'CONTINUE' for the ON_ERROR option. For more information on loading options, please run 'info loading_data' in a SQL client.
[2023-03-07T18:45:42.215+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Ingest_to_Snowflake, task_id=copy_into_results_table, execution_date=20230307T182020, start_date=20230307T184540, end_date=20230307T184542
[2023-03-07T18:45:42.228+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 186 for task copy_into_results_table (100080 (22000): 01aacac5-0000-0ab5-0000-1e09000131e2: Number of columns in file (14) does not match that of the corresponding table (9), use file format option error_on_column_count_mismatch=false to ignore this error
  File 'results.csv', line 3, character 1
  Row 1 starts at line 2, column "RESULTS"[14]
  If you would like to continue loading when an error is encountered, use other values such as 'SKIP_FILE' or 'CONTINUE' for the ON_ERROR option. For more information on loading options, please run 'info loading_data' in a SQL client.; 11998)
[2023-03-07T18:45:42.236+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-07T18:45:42.255+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
